// Generates docs/generated/db-schema.md from src/LifeManager.jsx:
// version constants, the `@schema` JSDoc block above `migrate`, freshState defaults, the migration ledger,
// storage keys, and a demo-data summary. Source is the single truth; this file is never hand-edited.
const fs = require("fs");
const path = require("path");
const S = require("./lib/source");

const src = S.readSrc();
const { text, lines } = src;
const grabLine = (re) => (text.match(re) || [])[1] || "?";

const version = grabLine(/\n  v: (\d+),/);
const diffRaw = grabLine(/const DIFF_RAW_VERSION = "([^"]+)"/);
const pointPolicy = grabLine(/const POINT_POLICY_VERSION = "([^"]+)"/);

// @schema block: /** @schema ... */ immediately above `const migrate`
const migLine = lines.findIndex((l) => l.startsWith("const migrate = "));
let schemaBlock = null;
if (migLine > 0) {
  let e = migLine - 1; while (e >= 0 && !lines[e].trim()) e--;
  if (lines[e].trim() === "*/") { let s = e; while (s >= 0 && !lines[s].startsWith("/**")) s--; if (s >= 0 && /@schema/.test(lines.slice(s, e + 1).join("\n"))) schemaBlock = lines.slice(s + 1, e).map((l) => l.replace(/^\s?\*\s?/, "")).join("\n"); }
}

// freshState defaults
const fresh = S.grabBlock("freshState", src);
const freshBody = fresh ? fresh.text.split("\n").slice(1, -1).join("\n") : "";

// migration ledger
const mig = S.grabBlock("migrate", src);
const ledger = [];
if (mig) {
  const ml = mig.text.split("\n");
  ml.forEach((l, i) => {
    const m = l.match(/if \(s\.v < (\d+)\) \{/);
    if (!m) return;
    const notes = [];
    for (let j = i + 1; j < Math.min(ml.length, i + 4); j++) { const c = ml[j].trim(); if (c.startsWith("//")) notes.push(c.replace(/^\/\/\s?/, "")); }
    ledger.push({ v: +m[1], note: notes.join(" ") || "(see source)" });
  });
}
const guard = /typeof s\.v !== "number"/.test(mig?.text || "") ? "Saves without a numeric `v` are normalised to 0 before the ledger runs." : "";

// storage keys
const keys = new Map();
for (const m of text.matchAll(/["`](liferpg-[\w-]*(?:\$\{[^}]+\})?[\w-]*)["`]/g)) {
  const line = text.slice(0, m.index).split("\n").length;
  const k = m[1];
  if (!keys.has(k)) keys.set(k, { line, section: S.sectionOf(lines, line) });
}
const KEY = grabLine(/const KEY = "([^"]+)"/);

// demo summary
const demo = S.grabBlock("demoState", src);
const count = (re) => ((demo?.text || "").match(re) || []).length;

const out = `<!-- GENERATED by tools/harness/gen-schema.js from src/LifeManager.jsx — do not edit by hand --><!-- src: CL-6 --><!-- src: SPEC-6 -->
# State schema and storage

| Constant | Value |
|---|---|
| State schema version (\`freshState.v\`) | ${version} |
| \`DIFF_RAW_VERSION\` (difficulty table version) | ${diffRaw} |
| \`POINT_POLICY_VERSION\` (exam payout policy) | ${pointPolicy} |
| Primary storage key \`KEY\` | \`${KEY}\` |

## Field reference

${schemaBlock ? "```js\n" + schemaBlock + "\n```" : "_No `/** @schema */` block found above `migrate` — add one (Phase 2) to document fields here._"}

## Fresh-state defaults (\`freshState\`)

\`\`\`js
${freshBody}
\`\`\`

## Migration ledger (\`migrate\`)

Blocks run in order; each is frozen once shipped ([Rule 12](../design-docs/core-beliefs.md#rule-12)). ${guard}

| From | Block note |
|---|---|
${ledger.map((l) => `| < v${l.v} → v${l.v} | ${l.note.replace(/\|/g, "\\|")} |`).join("\n")}

## Storage keys (\`liferpg-*\`, frozen for data compatibility)

| Key pattern | First use (line) | Section |
|---|---|---|
${[...keys.entries()].map(([k, v]) => `| \`${k}\` | ${v.line} | ${v.section || "-"} |`).join("\n")}

## Demo data (\`demoState\`)

Areas: ${count(/name: "[^"]+", grade: \d/g)} · goals: ${count(/krs: \[/g)} · tasks with a goal: ${count(/goalId:/g)} · cert milestones: ${count(/isCert: true/g)} · exam milestones: ${count(/isExam: true/g)}.
`;
const dest = path.join(S.ROOT, "docs", "generated", "db-schema.md");
fs.mkdirSync(path.dirname(dest), { recursive: true });
fs.writeFileSync(dest, out);
console.log(`db-schema.md: v${version}, ${ledger.length} migration blocks, ${keys.size} storage keys${schemaBlock ? "" : " (no @schema block yet)"}`);
