// Vite plugin: writes dist/sw.js at build time with the hashed asset list and a build id.
// Hashed assets are immutable, so they are cache-first; the entry document is network-first with a
// cache fallback, which is what makes the app open in airplane mode without ever serving a stale build.
// No new dependency: the service worker is a plain string, generated from the bundle Rollup produced.
// `skipWaiting` + `claim` stay so a new build is complete and consistent on the next open; the page is
// never reloaded by the app (`src/main.jsx` registers the worker and does nothing on a takeover).

const swSource = (buildId, critical, optional) => `/* generated by tools/harness/gen-sw.js — do not edit */
const BUILD = ${JSON.stringify(buildId)};
const CACHE = "life-manager-" + BUILD;
// Without these the app cannot start offline, so a failure here must fail the install.
const CRITICAL = ${JSON.stringify(critical, null, 2)};
// Nice to have. Fetched one by one so a single miss cannot wipe out offline support entirely.
const OPTIONAL = ${JSON.stringify(optional, null, 2)};
const PRECACHE = CRITICAL.concat(OPTIONAL);

self.addEventListener("install", (e) => {
  e.waitUntil((async () => {
    const c = await caches.open(CACHE);
    await c.addAll(CRITICAL);
    await Promise.allSettled(OPTIONAL.map((u) => c.add(u)));
    await self.skipWaiting();
  })());
});

self.addEventListener("activate", (e) => {
  e.waitUntil((async () => {
    for (const k of await caches.keys()) if (k !== CACHE) await caches.delete(k);
    await self.clients.claim();
  })());
});

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  // The document: network first so a deploy is picked up, cache second so airplane mode still opens.
  if (req.mode === "navigate") {
    e.respondWith((async () => {
      try {
        const fresh = await fetch(req);
        const c = await caches.open(CACHE);
        c.put("./", fresh.clone());
        return fresh;
      } catch {
        const c = await caches.open(CACHE);
        return (await c.match("./")) || (await c.match(PRECACHE[0])) || Response.error();
      }
    })());
    return;
  }

  // Hashed build assets: cache first, and fill the cache on a miss.
  e.respondWith((async () => {
    const c = await caches.open(CACHE);
    const hit = await c.match(req, { ignoreSearch: true });
    if (hit) return hit;
    try {
      const fresh = await fetch(req);
      if (fresh.ok && fresh.type === "basic") c.put(req, fresh.clone());
      return fresh;
    } catch {
      return Response.error();
    }
  })());
});
`;

// `buildId` is passed in so the caller decides how stable it is; the hashed file names already change
// per build, but the id is what evicts the old cache on activate.
function swPlugin({ buildId } = {}) {
  return {
    name: "life-manager-sw",
    apply: "build",
    generateBundle(_, bundle) {
      const files = Object.keys(bundle).filter((f) => /\.(js|css)$/.test(f));
      const critical = ["./", ...files.map((f) => "./" + f)];
      const optional = ["./manifest.webmanifest", "./icon.svg", "./icons/icon-192.png", "./icons/icon-512.png"];
      const id = buildId || String(Date.now());
      this.emitFile({ type: "asset", fileName: "sw.js", source: swSource(id, critical, optional) });
    },
  };
}

module.exports = { swPlugin, swSource };
